### ISSUE TITLE
Links don't work in a item label with a dot (.) or a double dot (:)

### ISSUE THREAD

**Issue by ivanhercaz** [SemanticMediaWiki/Mermaid#15]
First of all, thank you very much @mwjames for develop this awesome extension. Very useful and easy to use!

### Setup and configuration

- Mermaid version: 1.0.1
- MediaWiki version: 1.30.0
- PHP version: 7.1.15
- Database system and version: 5.6.39-cll-lve

### Issue

The problem is that I can't use dots or double dots in the labels of the items (check the below link to the SMW Sandbox). I installed Mermaid as the documentation said, it works fine at this moments, excepting this little error.

This is the only trace in the console that I have directly identified with Mermaid:
```
JQMIGRATE: Migrate is installed with logging active, version 3.0.1-pre  load.php:10295:4
JQMIGRATE: jQuery.fn.delegate() is deprecated  load.php:10344:4
console.trace():  load.php:10346
	migrateWarn http://cultport.ivanhercaz.com/load.php:10346:5
	.delegate http://cultport.ivanhercaz.com/load.php:10760:3
	delegate http://cultport.ivanhercaz.com/extensions/SemanticMediaWiki/res/jquery/jquery.qtip.js:1387:2
	<anónimo> http://cultport.ivanhercaz.com/extensions/SemanticMediaWiki/res/jquery/jquery.qtip.js:1660:2
	resolve/</mightThrow http://cultport.ivanhercaz.com/load.php:3583:21
	resolve/</process< http://cultport.ivanhercaz.com/load.php:3651:12
Use of "mermaid" is deprecated. Use mw.config instead.  load.php:11392:8
Use of "mermaid" is deprecated. Use mw.config instead.  load.php:11385:8
Use of "mermaid" is deprecated. Use mw.config instead. load.php:11385:8
Use of "mermaid" is deprecated. Use mw.config instead. load.php:11385:8
```

Steps to reproduce the observation: [Mermaid Test - graph with links with dots in labels](https://sandbox.semantic-mediawiki.org/wiki/Mermaid_Test_-_graph_with_links_with_dots_in_labels).

Regards,
Iván

**Comment by s7eph4n** [comment]
This is what I get:
![image](https://user-images.githubusercontent.com/2829850/38173039-9e664890-35b7-11e8-804c-6a76e9f6d951.png)

**Comment by mwjames** [comment]
> It should work, because in the live editor of MermaidJS it works fine

The live editor version uses 8.0.0-rc.6 and with that in mind I did a
quick test on the clicking issue replacing 7.0.5 with 8.0.0-rc.6
locally and it seems to resolve the issue.

8.0 [0] hasn't been released yet so for now 7.0.5 remains the bundled version.

[0] https://github.com/knsv/mermaid/issues/642
[1] https://unpkg.com/mermaid@8.0.0-rc.6/dist/mermaid.min.js
[2] https://unpkg.com/d3@4.0.0/build/d3.min.js

**Comment by kghbln** [comment]
Mermaid 2.0.0 has just been released. If I interpret correctly this issue should be resolved now that the Mermaid extension ships with mermaid 8.0.0. Anyways since it is an upsteam issue the Mermaid extensions cannot do anything about it.

**Comment by gesinn-it** [comment]
Issue still occurs with Mermaid 2.1.0 (last version supporting MW 1.31) when having a colon (:) in the title.

TODO: 
- test with current Mermaid 3.0.1 on MW 1.35
- heck, if this is covered by a test

**Comment by kghbln** [comment]
Working now.
